import type { Metadata } from "next";
import { favicon } from "../assets/images/financial";

export const metadata: Metadata = {
  title: "Tune Forge",
  description: "Generated by create next app",
  icons: {
    icon: `${favicon}`,
    shortcut: `${favicon}`,
    apple: "/apple-icon.png",
    other: {
      rel: "apple-touch-icon-precomposed",
      url: "/apple-touch-icon-precomposed.png",
    },
  },
};

export default function PortfolioLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <>{children}</>
    </>
  );
}
