import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Professional Portfolio",
  description: "Generated by create next app",
};

export default function PortfolioLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <>{children}</>
    </>
  );
}
