import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Finacial",
  description: "Generated by create next app",
  icons: {
    icon: "/financel-favicon.svg",
  },
};

export default function FinancialLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
