version: "3.8"
services:
  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - "3001:3000"
  #   restart: always

  frontend-web:
    image: ghcr.io/cardosobelempb/workspace-tailwind:main
    container_name: frontend-web
    networks:
      - network_public
    restart: always
    ports:
      - 3001:3000
    environment:
      NODE_ENV: prod
      NEXT_PUBLIC_API_URL: https://tailwind.surb.com.br
      SECRET_KEY_PROD: my-prod-secret-key
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend-web.rule=Host(`tailwind.surb.com.br`)
        - traefik.http.routers.frontend-web.entrypoints=websecure
        - traefik.http.routers.frontend-web.tls.certresolver=letsencryptresolver
        - traefik.http.routers.frontend-web.priority=1
        - traefik.http.routers.frontend-web.service=evolution_api
        - traefik.http.services.frontend-web.loadbalancer.server.port=8080
        - traefik.http.services.frontend-web.loadbalancer.passHostHeader=true

  # frontend-admin:
  #   build: ./frontend-admin
  #   container_name: frontend-admin
  #   ports:
  #     - "3002:3000"
  #   restart: always

networks:
  network_public:
    external: true
    name: network_public
