version: "3.8"

services:
  tailwind-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      SECRET_KEY_DEV: my-dev-secret-key
    volumes:
      - .:/app
    command: npm run dev

  tailwind-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3000
    environment:
      NODE_ENV: prod
      NEXT_PUBLIC_API_URL: https://tailwind.surb.com.br
      SECRET_KEY_PROD: my-prod-secret-key
