import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tune Forge",
  description: "Generated by create next app",
  icons: {
    icon: "/music.svg",
  },
};

if (typeof window !== "undefined") {
  Math.random();
}

export default function TuneForgeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="*:font-barlow-condensed bg-df-blue selection:bg-df-blue selection:text-df-golden">
      {children}
    </div>
  );
}
