version: "3.8"

services:
  # traefik:
  #   image: traefik:latest
  #   container_name: traefik
  #   restart: always
  #   command:
  #     - "--api.dashboard=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #     - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
  #     - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
  #     - "--certificatesresolvers.letsencryptresolver.acme.email=seu-email@dominio.com"
  #     - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./letsencrypt:/letsencrypt
  #   networks:
  #     - network_public

  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - network_public

  # backend:
  #   build:
  #     context: https://github.com/seu-usuario/seu-repo-backend.git
  #   container_name: backend
  #   restart: always
  #   environment:
  #     DATABASE_URL: postgres://user:password@postgres:5432/mydb
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.backend.rule=Host(`tbpanel.surb.com.br`)"
  #     - "traefik.http.routers.backend.entrypoints=websecure"
  #     - "traefik.http.routers.backend.tls.certresolver=letsencryptresolver"
  #     - "traefik.http.services.backend.loadbalancer.server.port=3000"
  #   networks:
  #     - network_public
  #   depends_on:
  #     - postgres

  frontend:
    build:
      context: https://github.com/cardosobelempb/workspace-tailwind/tree/main/tailwind-example
    container_name: frontend
    restart: always
    # environment:
    #   DATABASE_URL: postgresql://user:password@postgres:5432/mydb
    #   ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
    #   DEFAULT_WORKSPACE_PLAN: UNLIMITED
    #   NEXTAUTH_URL: https://tbpanel.surb.com.br
    #   NEXT_PUBLIC_VIEWER_URL: https://tbchat.surb.com.br
    #   NEXTAUTH_URL_INTERNAL: http://localhost:3000
    #   DISABLE_SIGNUP: true
    #   ADMIN_EMAIL: contact@surb.com.br
    #   NEXT_PUBLIC_SMTP_FROM: "Surb Bot <contato@surb.com.br>"
    #   SMTP_AUTH_DISABLED: false
    #   SMTP_USERNAME: contato@surb.com.br
    #   SMTP_PASSWORD: ${SMTP_PASSWORD}
    #   SMTP_HOST: smtp.hostinger.com
    #   SMTP_PORT: 465
    #   SMTP_SECURE: true
    #   S3_ACCESS_KEY: ${S3_ACCESS_KEY}
    #   S3_SECRET_KEY: ${S3_SECRET_KEY}
    #   S3_BUCKET: typebot
    #   S3_ENDPOINT: mp.surb.com.br
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`tailwind.surb.com.br`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=6000"
    networks:
      - network_public
    # depends_on:
    #   - backend

# volumes:
#   postgres_data:

networks:
  network_public:
    external: true
    name: network_public
